stages:
 - backup_dev
 - prepare_dev
 - clean_dev
 - build_dev
 - forever_dev
 - deploy_dev
 - backup_prod
 - prepare_prod
 - clean_prod
 - build_prod
 - forever_prod
 - deploy_prod
 - backup_backup
 - prepare_backup
 - clean_backup
 - build_backup
 - forever_backup
 - deploy_backup
 - failure_dev
 - success_dev
 - failure_prod
 - success_prod
 - failure_backup
 - success_backup

backup_job_dev:
 stage: backup_dev
 script:
  - cd D:/KumonCheckINApi
  - echo backup stage at %time% and directory %cd% 
  - xcopy "D:\KumonCheckINApi\log" "D:\KumonCheckINApi_LOG\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_Log\log" /I/Y
  - cd "D:\KumonCheckINApi_LOG\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_Log\log"
  - if exist  "err.log" rename err.log  "%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_err.log"
  - if exist  "out.log" rename out.log  "%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_out.log"
  - echo current timetest %time%
 variables:
  GIT_STRATEGY: none
 tags:
  - Dev
 only:
  - dev 

prepare_job_dev:
 stage: prepare_dev
 script:
  - cd D:/
  - rd D:\KumonCheckINApi_BK /s /q
  - xcopy "D:\KumonCheckINApi" "D:\KumonCheckINApi_BK\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%_BK\" /I/E/Y/EXCLUDE:D:\KumonCheckINApi\exclusion.txt
  - cd "D:\KumonCheckINApi_BK\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%_BK\"
  - del package-lock.json
  - cd D:/KumonCheckINApi
  - echo prepare stage at %time% and directory %cd%
  - git reset --hard HEAD~
  - git pull
 variables:
  GIT_STRATEGY: none
 tags:
  - Dev
 only:
  - dev  

clean_job_dev:
 stage: clean_dev
 script:
  - echo clean stage at %time% and directory %cd%
  - if exist node_modules rd /s /q node_modules
  - del package-lock.json
  - cd D:/KumonCheckINApi/log
  - echo %cd%
  - del *.log
 variables:
  GIT_STRATEGY: none
 tags:
  - Dev
 only:
  - dev 
  
build_job_dev:
 stage: build_dev
 script:
  - cd D:/KumonCheckINApi
  - echo build stage at %time% and directory %cd%
  - npm install
 variables:
  GIT_STRATEGY: none
 tags:
  - Dev
 only:
  - dev  
  
forever_job_dev:
 stage: forever_dev
 script:
  - cd D:/KumonCheckINApi
  - echo forever stage at %time% and directory %cd%
  - npm run win_ci_function_dev forever KumonCheckINApi
 variables:
  GIT_STRATEGY: none
 tags:
  - Dev
 only:
  - dev  

deploy_job_dev:
 stage: deploy_dev
 script:
  - cd D:/KumonCheckINApi/config
  - FOR /F "delims=':' tokens=2" %%a in ('ipconfig ^| find "IPv4"') do set _IPAddress=%%a
  - echo %_IPAddress%
  - if exist %_IPAddress%.js copy %_IPAddress%.js D:\KumonCheckINApi\Config.js
  - cd D:/KumonCheckINApi
  - echo deploy stage at %time% and directory %cd%
  - npm run win_forever_dev
 variables:
  GIT_STRATEGY: none
 tags:
  - Dev
 only:
  - dev  

failure_job_dev:
 stage: failure_dev
 script:
  - cd D:/KumonCheckINApi
  - echo failure stage at %time% and directory %cd%
 variables:
  GIT_STRATEGY: none
 when: on_failure
 tags:
  - Dev

success_job_dev:
 stage: success_dev
 script:
  - cd D:/KumonCheckINApi
  - echo success stage at %time% and directory %cd%
 variables:
  GIT_STRATEGY: none
 when: on_success
 tags:
  - Dev




backup_job_prod:
 stage: backup_prod
 script:
  - cd D:/KumonCheckINApi
  - echo backup stage at %time% and directory %cd%
  - xcopy "D:\KumonCheckINApi\log" "D:\KumonCheckINApi_LOG\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_Log\log" /I
  - cd "D:\KumonCheckINApi_LOG\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_Log\log"
  - if exist  "err.log" rename err.log  "%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_err.log"
  - if exist  "out.log" rename out.log  "%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_out.log"
  - echo current timetest %time%
 variables:
  GIT_STRATEGY: none
 tags:
  - Prod
 only:
  - master  

prepare_job_prod:
 stage: prepare_prod
 script:
  - cd D:/
  - rd D:\KumonCheckINApi_BK /s /q
  - xcopy "D:\KumonCheckINApi" "D:\KumonCheckINApi_BK\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%_BK\" /I/E/Y/EXCLUDE:D:\KumonCheckINApi\exclusion.txt
  - cd "D:\KumonCheckINApi_BK\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%_BK\"
  - del package-lock.json
  - cd D:/KumonCheckINApi
  - echo prepare stage at %time% and directory %cd%
  - git reset --hard HEAD~
  - git pull
 variables:
  GIT_STRATEGY: none
 tags:
  - Prod
 only:
  - master   
 
clean_job_prod:
 stage: clean_prod
 script:
  - echo clean stage at %time% and directory %cd%
  - if exist node_modules rd /s /q node_modules
  - del package-lock.json
  - cd D:/KumonCheckINApi/log
  - echo %cd%
  - del *.log
 variables:
  GIT_STRATEGY: none
 tags:
  - Prod
 only:
  - master  
  
build_job_prod:
 stage: build_prod
 script:
  - cd D:/KumonCheckINApi
  - echo build stage at %time% and directory %cd%
  - npm install
 variables:
  GIT_STRATEGY: none
 tags:
  - Prod
 only:
  - master  
  
forever_job_prod:
 stage: forever_prod
 script:
  - cd D:/KumonCheckINApi
  - echo forever stage at %time% and directory %cd%
  - npm run win_ci_function_prod forever KumonCheckINApi
 variables:
  GIT_STRATEGY: none
 tags:
  - Prod
 only:
  - master  

deploy_job_prod:
 stage: deploy_prod
 script:
  - cd D:/KumonCheckINApi/config
  - FOR /F "delims=':' tokens=2" %%a in ('ipconfig ^| find "IPv4"') do set _IPAddress=%%a
  - echo %_IPAddress%
  - if exist %_IPAddress%.js copy %_IPAddress%.js D:\KumonCheckINApi\Config.js
  - cd D:/KumonCheckINApi
  - echo deploy stage at %time% and directory %cd%
  - npm run win_forever_prod
 variables:
  GIT_STRATEGY: none
 tags:
  - Prod
 only:
  - master 


failure_job_prod:
 stage: failure_prod
 script:
  - cd D:/KumonCheckINApi
  - echo failure stage at %time% and directory %cd%
 variables:
  GIT_STRATEGY: none
 when: on_failure
 tags:
  - Prod
 only:
  - master 

success_job_prod:
 stage: success_prod
 script:
  - cd D:/KumonCheckINApi
  - echo success stage at %time% and directory %cd%
 variables:
  GIT_STRATEGY: none
 when: on_success
 tags:
  - Prod
 only:
  - master
  
  

backup_job_backup:
 stage: backup_backup
 script:
  - cd D:/KumonCheckINApi
  - echo backup stage at %time% and directory %cd% 
  - xcopy "D:\KumonCheckINApi\log" "D:\KumonCheckINApi_LOG\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_Log\log" /I/Y
  - cd "D:\KumonCheckINApi_LOG\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_Log\log"
  - if exist  "err.log" rename err.log  "%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_err.log"
  - if exist  "out.log" rename out.log  "%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%time:~0,2%%time:~3,2%_out.log"
  - echo current timetest %time%
 variables:
  GIT_STRATEGY: none
 tags:
  - Backup
 only:
  - master 

prepare_job_backup:
 stage: prepare_backup
 script:
  - cd D:/
  - rd D:\KumonCheckINApi_BK /s /q
  - xcopy "D:\KumonCheckINApi" "D:\KumonCheckINApi_BK\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%_BK\" /I/E/Y/EXCLUDE:D:\KumonCheckINApi\exclusion.txt
  - cd "D:\KumonCheckINApi_BK\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%_BK\"
  - del package-lock.json
  - cd D:/KumonCheckINApi
  - echo prepare stage at %time% and directory %cd%
  - git reset --hard HEAD~
  - git pull
 variables:
  GIT_STRATEGY: none
 tags:
  - Backup
 only:
  - master  

clean_job_backup:
 stage: clean_backup
 script:
  - echo clean stage at %time% and directory %cd%
  - if exist node_modules rd /s /q node_modules
  - del package-lock.json
  - cd D:/KumonCheckINApi/log
  - echo %cd%
  - del *.log
 variables:
  GIT_STRATEGY: none
 tags:
  - Backup
 only:
  - master 
  
build_job_backup:
 stage: build_backup
 script:
  - cd D:/KumonCheckINApi
  - echo build stage at %time% and directory %cd%
  - npm install
 variables:
  GIT_STRATEGY: none
 tags:
  - Backup
 only:
  - master  
  
forever_job_backup:
 stage: forever_backup
 script:
  - cd D:/KumonCheckINApi
  - echo forever stage at %time% and directory %cd%
  - npm run win_ci_function_prod forever KumonCheckINApi
 variables:
  GIT_STRATEGY: none
 tags:
  - Backup
 only:
  - master  

deploy_job_backup:
 stage: deploy_backup
 script:
  - cd D:/KumonCheckINApi/config
  - FOR /F "delims=':' tokens=2" %%a in ('ipconfig ^| find "IPv4"') do set _IPAddress=%%a
  - echo %_IPAddress%
  - if exist %_IPAddress%.js copy %_IPAddress%.js D:\KumonCheckINApi\Config.js
  - cd D:/KumonCheckINApi
  - echo deploy stage at %time% and directory %cd%
  - npm run win_forever_prod
 variables:
  GIT_STRATEGY: none
 tags:
  - Backup
 only:
  - master  

failure_job_backup:
 stage: failure_backup
 script:
  - cd D:/KumonCheckINApi
  - echo failure stage at %time% and directory %cd%
 variables:
  GIT_STRATEGY: none
 when: on_failure
 tags:
  - Backup
 only:
  - master

success_job_backup:
 stage: success_backup
 script:
  - cd D:/KumonCheckINApi
  - echo success stage at %time% and directory %cd%
 variables:
  GIT_STRATEGY: none
 when: on_success
 tags:
  - Backup
 only:
  - master

